import Kazuto from '../imagens/kirito.jpg';
import Asuna from '../imagens/asuna.png';

const muitoRaro = 'muito raro';

const saoCharacters = [
  {
    cardName: 'Kazuto Kirigaya',
    cardDescription: 'Kirito',
    cardAttr1: 80,
    cardAttr2: 65,
    cardAttr3: 63,
    cardImage: Kazuto,
    cardRare: muitoRaro,
    cardTrunfo: true,
  },
  {
    cardName: 'Asuna Yuuki',
    cardDescription: 'Asuna',
    cardAttr1: 68,
    cardAttr2: 70,
    cardAttr3: 72,
    cardImage: Asuna,
    cardRare: muitoRaro,
    cardTrunfo: false,
  },
  {
    cardName: 'Shino Asada',
    cardDescription: 'Sinon',
    cardAttr1: 72,
    cardAttr2: 43,
    cardAttr3: 35,
    cardImage: '',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Alice Zuberg',
    cardDescription: '',
    cardAttr1: 68,
    cardAttr2: 39,
    cardAttr3: 65,
    cardImage: '',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Eugeo',
    cardDescription: '',
    cardAttr1: 52,
    cardAttr2: 35,
    cardAttr3: 36,
    cardImage: '',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Yuuki Konno',
    cardDescription: '',
    cardAttr1: 70,
    cardAttr2: 70,
    cardAttr3: 70,
    cardImage: '',
    cardRare: muitoRaro,
    cardTrunfo: false,
  },
  {
    cardName: 'Yui',
    cardDescription: 'IA',
    cardAttr1: 0,
    cardAttr2: 0,
    cardAttr3: 0,
    cardImage: '',
    cardRare: muitoRaro,
    cardTrunfo: false,
  },
  {
    cardName: 'Ryoutarou Tsuboi',
    cardDescription: 'Klein',
    cardAttr1: 55,
    cardAttr2: 37,
    cardAttr3: 68,
    cardImage: '',
    cardRare: 'comum',
    cardTrunfo: false,
  },
  {
    cardName: 'Keiko Ayano',
    cardDescription: 'Silica',
    cardAttr1: 29,
    cardAttr2: 15,
    cardAttr3: 28,
    cardImage: '',
    cardRare: 'comum',
    cardTrunfo: false,
  },
  {
    cardName: 'Kirigaya Suguha',
    cardDescription: 'Leafa',
    cardAttr1: 59,
    cardAttr2: 17,
    cardAttr3: 48,
    cardImage: '',
    cardRare: 'comum',
    cardTrunfo: false,
  },
  {
    cardName: 'Rika Shinozaki',
    cardDescription: 'Lisbeth',
    cardAttr1: 59,
    cardAttr2: 17,
    cardAttr3: 48,
    cardImage: '',
    cardRare: 'comum',
    cardTrunfo: false,
  },
  {
    cardName: 'Sachi',
    cardDescription: '',
    cardAttr1: 59,
    cardAttr2: 17,
    cardAttr3: 48,
    cardImage: '',
    cardRare: 'comum',
    cardTrunfo: false,
  },
  {
    cardName: 'Akihiko Kayaba',
    cardDescription: 'Heathcliff',
    cardAttr1: 90,
    cardAttr2: 90,
    cardAttr3: 90,
    cardImage: '',
    cardRare: muitoRaro,
    cardTrunfo: false,
  },
  {
    cardName: 'Andrew Gilbert Mills',
    cardDescription: 'Agil',
    cardAttr1: 52,
    cardAttr2: 23,
    cardAttr3: 38,
    cardImage: '',
    cardRare: 'comum',
    cardTrunfo: false,
  },
  {
    cardName: 'Quinella',
    cardDescription: '',
    cardAttr1: 59,
    cardAttr2: 17,
    cardAttr3: 48,
    cardImage: '',
    cardRare: 'comum',
    cardTrunfo: false,
  },
  {
    cardName: 'Yuna',
    cardDescription: '',
    cardAttr1: 59,
    cardAttr2: 17,
    cardAttr3: 48,
    cardImage: '',
    cardRare: 'comum',
    cardTrunfo: false,
  },
  {
    cardName: 'Bercouli Synthesis One',
    cardDescription: '',
    cardAttr1: 59,
    cardAttr2: 17,
    cardAttr3: 48,
    cardImage: '',
    cardRare: 'comum',
    cardTrunfo: false,
  },
  {
    cardName: 'Argo',
    cardDescription: '',
    cardAttr1: 59,
    cardAttr2: 17,
    cardAttr3: 48,
    cardImage: '',
    cardRare: 'comum',
    cardTrunfo: false,
  },
  {
    cardName: 'Tiese Shtolienen',
    cardDescription: '',
    cardAttr1: 59,
    cardAttr2: 17,
    cardAttr3: 48,
    cardImage: '',
    cardRare: 'comum',
    cardTrunfo: false,
  },
  {
    cardName: 'Ronie Arabel ',
    cardDescription: '',
    cardAttr1: 59,
    cardAttr2: 17,
    cardAttr3: 48,
    cardImage: '',
    cardRare: 'comum',
    cardTrunfo: false,
  },
];

export default saoCharacters;
